# Fast Training Configuration (for quick experiments)
# @package _global_
name: fast

# Training hyperparameters
batch_size: 512
learning_rate: 0.001
weight_decay: 1e-4
epochs: 10
patience: 3
min_delta: 1e-3

# Optimizer settings
optimizer:
  type: "adam"
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: false

# Scheduler settings
scheduler:
  type: "exponential"
  gamma: 0.95

# Loss function settings
loss:
  type: "bce"
  reduction: "mean"

# Validation settings
validation:
  val_ratio: 0.2
  val_batch_size: 1024
  val_frequency: 1
  early_stopping: true

# Evaluation metrics
metrics: ["rmse", "mae", "accuracy"]
top_k: [10]