# Production Training Configuration (thorough training)
# @package _global_
name: production

# Training hyperparameters
batch_size: 256
learning_rate: 0.005
weight_decay: 5e-5
epochs: 100
patience: 10
min_delta: 1e-5

# Optimizer settings
optimizer:
  type: "adam"
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: true

# Scheduler settings
scheduler:
  type: "cosine"
  T_max: 100
  eta_min: 1e-6

# Loss function settings
loss:
  type: "bce"
  reduction: "mean"

# Validation settings
validation:
  val_ratio: 0.2
  val_batch_size: 512
  val_frequency: 1
  early_stopping: true

# Evaluation metrics
metrics: ["rmse", "mae", "precision@5", "precision@10", "precision@20", "recall@5", "recall@10", "recall@20", "ndcg@10", "f1"]
top_k: [5, 10, 20, 50]