# Main configuration file for Hydra-based training
# Usage: python train_hydra.py --config-path conf --config-name config

defaults:
  - model: collaborative  # Default model
  - train: default       # Default training config
  - data: default        # Default data config
  - optimizer: adam      # Default optimizer config
  - experiment: null     # Optional experiment config
  - _self_

# Experiment settings
experiment:
  name: "movie_recommendation"
  tags: ["collaborative_filtering", "pytorch"]
  notes: "Training movie recommendation models with different configurations"

# Global settings
seed: 42
device: "auto"  # auto, cpu, cuda

# Hydra settings
hydra:
  run:
    dir: "outputs/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "outputs/${experiment.name}/multirun/${now:%Y-%m-%d_%H-%M-%S}"
    subdir: "${hydra:job.num}_${model.name}"
  job:
    name: "${experiment.name}_${model.name}"