# Comprehensive Optuna Sweeper for Production Optimization
# Usage: python train_hydra.py -m hydra/sweeper=optuna_comprehensive

# @package hydra.sweeper
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

# Production study settings
study_name: "comprehensive_model_optimization"
storage: "sqlite:///optuna_comprehensive.db"  # Persistent storage
n_trials: 50
n_jobs: 1

# Minimize validation RMSE
direction: minimize

# Comprehensive search space
search_space:
  # Model architecture
  model.embedding_dim:
    type: choice
    choices: [32, 50, 64, 80, 100, 128]
  
  model.dropout:
    type: float
    low: 0.0
    high: 0.6
    step: 0.05
  
  # Hybrid model specific (if applicable)
  model.collaborative_weight:
    type: float
    low: 0.3
    high: 0.9
    step: 0.1
  
  # Training hyperparameters
  train.learning_rate:
    type: float
    low: 0.0001
    high: 0.1
    log: true
  
  train.batch_size:
    type: choice
    choices: [128, 256, 512, 1024]
  
  train.weight_decay:
    type: float
    low: 1e-6
    high: 1e-2
    log: true
  
  train.epochs:
    type: int
    low: 15
    high: 40
    step: 5

# Advanced pruning for efficiency
pruner:
  _target_: optuna.pruners.HyperbandPruner
  min_resource: 3
  max_resource: 20
  reduction_factor: 3

# Advanced sampler with multi-objective support
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42
  n_startup_trials: 10
  n_ei_candidates: 24